### ISSUE TITLE
Incorrect file path in LoanPortfolioStressTesting.mlx

### ISSUE THREAD

**Issue by GBress** [mathworks/Database-Explorer-for-IIASA#3]
Dear All,

There seems to be a bug in the script "LoanPortfolioStressTesting.mlx", with the following error messages below appearing when running line 10 (GCAM = e.getTimeSeries(...)). Root cause seems to be row 122 of "LIMITSconnection.m", which points to a local path to load scenario variables:

"AllValues = readtable("C:\Users\ebenetce\OneDrive - MathWorks\AEProjects\Climate\iam-explorer\examples\LIMITSPUBLIC_2014-10-13.csv", opts);"

Loading from current folder fixed the issue for me:

"AllValues = readtable("LIMITSPUBLIC_2014-10-13.csv", opts);"

Please let me know if you need more information on the issue.

Best,

GBress

"Error using [matlab.io.ImportOptions/readtable](matlab:matlab.internal.language.introspective.errorDocCallback('matlab.io.ImportOptions/readtable', 'C:\Program Files\MATLAB\R2021a\toolbox\shared\io\general\+matlab\+io\@ImportOptions\ImportOptions.m', 667)) ([line 667](matlab: opentoline('C:\Program Files\MATLAB\R2021a\toolbox\shared\io\general\+matlab\+io\@ImportOptions\ImportOptions.m',667,0)))
Unable to find or open 'C:\Users\ebenetce\OneDrive - MathWorks\AEProjects\Climate\iam-explorer\examples\LIMITSPUBLIC_2014-10-13.csv'. Check the path and filename or file permissions.

Error in [iam.data.LIMITSconnection/getBulkData](matlab:matlab.internal.language.introspective.errorDocCallback('iam.data.LIMITSconnection/getBulkData', 'C:\Users\giaco\OneDrive\Documenti\Follow upz\PHD\20. Miscellaneours\Lessons Nice_Dec22\Climate-IAM-Explorer-master (2)\Climate-IAM-Explorer-master\tbx\+iam\+data\LIMITSconnection.m', 122)) ([line 122](matlab: opentoline('C:\Users\giaco\OneDrive\Documenti\Follow upz\PHD\20. Miscellaneours\Lessons Nice_Dec22\Climate-IAM-Explorer-master (2)\Climate-IAM-Explorer-master\tbx\+iam\+data\LIMITSconnection.m',122,0)))
                AllValues = readtable("C:\Users\ebenetce\OneDrive - MathWorks\AEProjects\Climate\iam-explorer\examples\LIMITSPUBLIC_2014-10-13.csv", opts);

Error in [iam.IAMEnvironment/getTimeSeries](matlab:matlab.internal.language.introspective.errorDocCallback('iam.IAMEnvironment/getTimeSeries', 'C:\Users\giaco\OneDrive\Documenti\Follow upz\PHD\20. Miscellaneours\Lessons Nice_Dec22\Climate-IAM-Explorer-master (2)\Climate-IAM-Explorer-master\tbx\+iam\IAMEnvironment.m', 76)) ([line 76](matlab: opentoline('C:\Users\giaco\OneDrive\Documenti\Follow upz\PHD\20. Miscellaneours\Lessons Nice_Dec22\Climate-IAM-Explorer-master (2)\Climate-IAM-Explorer-master\tbx\+iam\IAMEnvironment.m',76,0)))
            ts = obj.Connection.getBulkData( ..."

**Comment by ebenetce** [comment]
Issue fixed in master branch, it will merge in the toolbox once I republish it with some other bug-fixes
