### ISSUE TITLE
Missing file in "LoanPortfolioStressTesting.mx"

### ISSUE THREAD

**Issue by GBress** [mathworks/Database-Explorer-for-IIASA#4]
Dear All,

There seems to be a missing file in the "LoanPortfolioStressTesting.mx" livescript. On row 146, the table "loanData.mat" is required but this .mat is not available in the example folder nor (to the best of my knowledge) in the rest of the folders. Thus the last cell can't be run. It is also not possible to obtain this .mat file from the source database (GEGI database), nor to easily transform the .xlsx that can be downloaded from GEGI in the format required by the code.

Please let me know if you need further information on the issue.

Best,

GBress

**Comment by ebenetce** [comment]
I added the missing file
